# Log4J-Fixer by Rhys
# https://github.com/notrhys/Log-4J-Exploit-Fix
punishments:
  enabled: true
  command: 'ipban %player% CVE-2021-44228'
notify:
  enabled: true
  permission: log4jfix.notify
  message: '&4[Log4J-Fix] &c%player% has been prevented from abusing Log4J 0 Day exploit'